# Generated by Django 3.2.8 on 2021-10-13 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('BUS', 'BUSINESS'), ('EN', 'ENGLISH'), ('FR', 'FRENCH'), ('GER', 'GERMAN'), ('GEO', 'GEOGRAPHY'), ('IR', 'IRISH'), ('MAT', 'MATHS'), ('SPA', 'SPANISH')], max_length=3)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('number_of_students', models.IntegerField(verbose_name=range(1, 15))),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=15)),
                ('sudent_email', models.EmailField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_slot', to='bookings.slot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutored_student', to='bookings.student')),
            ],
            options={
                'ordering': ['booking_time'],
            },
        ),
    ]
