# Generated by Django 3.2.8 on 2021-10-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_students',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='title',
            field=models.CharField(choices=[('BUS', 'BUSINESS'), ('EN', 'ENGLISH'), ('FR', 'FRENCH'), ('GER', 'GERMAN'), ('GEO', 'GEOGRAPHY'), ('IR', 'IRISH'), ('MAT', 'MATHS'), ('SPA', 'SPANISH')], default='BUS', max_length=3),
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
