# Generated by Django 3.2.8 on 2021-10-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20211013_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sudent_email',
            new_name='student_email',
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
