# Generated by Django 3.2.8 on 2021-10-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20211014_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
