# Generated by Django 3.2.8 on 2021-10-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='edited',
            new_name='approved',
        ),
    ]
